// This file is generated by ttrpc-compiler 0.7.0. Do not edit
// @generated

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unknown_lints)]
#![allow(clipto_camel_casepy)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
#![allow(clippy::all)]
use protobuf::{CodedInputStream, CodedOutputStream, Message};
use std::collections::HashMap;
use std::sync::Arc;
use async_trait::async_trait;

#[derive(Clone)]
pub struct HelloServiceClient {
    client: ::ttrpc::r#async::Client,
}

impl HelloServiceClient {
    pub fn new(client: ::ttrpc::r#async::Client) -> Self {
        HelloServiceClient {
            client,
        }
    }

    pub async fn hello_world(&self, ctx: ttrpc::context::Context, req: &super::api::HelloRequest) -> ::ttrpc::Result<super::api::HelloResponse> {
        let mut cres = super::api::HelloResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "example.HelloService", "HelloWorld", cres);
    }
}

struct HelloWorldMethod {
    service: Arc<dyn HelloService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for HelloWorldMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, api, HelloRequest, hello_world);
    }
}

#[async_trait]
pub trait HelloService: Sync {
    async fn hello_world(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::api::HelloRequest) -> ::ttrpc::Result<super::api::HelloResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/example.HelloService/HelloWorld is not supported".to_string())))
    }
}

pub fn create_hello_service(service: Arc<dyn HelloService + Send + Sync>) -> HashMap<String, ::ttrpc::r#async::Service> {
    let mut ret = HashMap::new();
    let mut methods = HashMap::new();
    let streams = HashMap::new();

    methods.insert("HelloWorld".to_string(),
                    Box::new(HelloWorldMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    ret.insert("example.HelloService".to_string(), ::ttrpc::r#async::Service{ methods, streams });
    ret
}
