[workspace]
members = ["src/client", "src/service","src/protos"]

[workspace.dependencies]
reqwest = { version = "0.11", features = ["json"] }
cpal = "0.14"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
rodio = "0.15"
ttrpc = "*"
prost-build  = "*"
ttrpc-codegen = "*"


