[package]
name = "assistant"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
cpal = "0.14"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
rodio = "0.15"
ttrpc = "*"

[build-dependencies]
prost-build  = "*"
ttrpc-codegen = "*"