[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
tokio = {workspace = true}
reqwest = {workspace = true}
serde = { version = "1.0", features = ["derive"] }
serde_json = {workspace = true}