# Chat template for different large models
[templates]
# Qwen chat template
[templates.qwen]
user = "<|im_start|>user\n{prompt}\n<|im_end|>"
assistant = "<|im_start|>assistant\n"
system = "<|im_start|>system\n{system_prompt}<|im_end|>"
chat_template = "{system}\n{user}\n{assistant}"

# DeepSeek chat template
[templates.deepseek]
user = "Human: {prompt}\n"
assistant = "Assistant: "
system = "{system_prompt}\n"
chat_template = "{system}{user}{assistant}"

# Default chat template
[templates.default]
user = "{prompt}"
assistant = "{response}"
system = "{system_prompt}"
chat_template = "{user}" 