[server]
ttrpc_addr = "unix:///tmp/ttrpc-test"
grpc_addr = "0.0.0.0:50051"

[speech_to_text]
model_path= "https://api.siliconflow.cn/v1/audio/transcriptions"
api_key = ""
model_name = "FunAudioLLM/SenseVoiceSmall"

[dialogue_model]
model_path="https://api.siliconflow.cn/v1/chat/completions"
api_key= ""
model_name= "Qwen/Qwen2.5-7B-Instruct"
stream = true
prompt_path= ""

[local_model]
enabled = true
wasm_path = "./wasmedge-ggml-llama-stream.wasm"
model_path = "./Meta-Llama-3-8B-Instruct.Q5_K_M.gguf"
n_gpu_layers = 100
ctx_size = 2048
instance_count = 2

[text_to_speech]
model_path= ""
