[server]
addr = "unix:///tmp/ttrpc-test"


[speech_to_text]
model_path= ""

[dialogue_model]
model_name= "ep-20250205152535-z4rzh"
api_key= ""
stream = true
prompt_path= ""
model_path="https://ark.cn-beijing.volces.com/api/v3/chat/completions"

[text_to_speech]
model_path= ""
