[server]
addr = "unix:///tmp/ttrpc-test"


[speech_to_text]
model_path= "https://api.siliconflow.cn/v1/audio/transcriptions"
api_key = ""
model_name = "FunAudioLLM/SenseVoiceSmall"

[dialogue_model]
model_path="https://api.siliconflow.cn/v1/chat/completions"
api_key= ""
model_name= "Qwen/Qwen2.5-7B-Instruct"
stream = true
prompt_path= ""


[text_to_speech]
model_path= ""
