[server]
ttrpc_addr = "unix:///tmp/ttrpc-test"
grpc_addr = "0.0.0.0:50051"
try_max_time = 3

[remote_server]
endpoints = ["http://0.0.0.0:50051"]
timeout = 5000  # milliseconds

[speech_to_text]
model_path= "https://api.siliconflow.cn/v1/audio/transcriptions"
api_key = ""
model_name = "FunAudioLLM/SenseVoiceSmall"

[dialogue_model]
knowledge_base = ""

[[dialogue_model.remote_models]]
enabled = true
priority = 3
model_path = "https://api.siliconflow.cn/v1/chat/completions"
model_name = "Qwen/Qwen2.5-7B-Instruct"
api_key= ""
stream = true
parameters = { temperature = "0.7", max_tokens = "2048" }

[[dialogue_model.local_models]]
enabled = true
priority = 1
wasm_path = "/home/hu/code/assistant/target/wasm32-wasi/release/wasme-ggml.wasm"
model_path = "/home/hu/code/assistant/models/qwen1_5-0_5b-chat-q2_k.gguf"
n_gpu_layers = 100
ctx_size = 2048
instance_count = 2





[text_to_speech]
model_path= ""
