[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = {workspace = true}
serde_json = {workspace = true}
tokio = {workspace = true}
ttrpc =  {workspace = true}
protos = {path = "../../protos"}